---
## Ansible Playbook to validate switch is running desired code version. 


- name: Validate Code Version
  hosts: office
  connection: local
  gather_facts: false
  ignore_unreachable: true
  vars_files:
    - vault.yml
  vars:
    ansible_network_cli_ssh_type: libssh
    cli:
      username: "{{ username }}"
      password: "{{ password }}"
    upgrade_ios_version: 15.2(7)E7
    switch_model: WS-C2960X
  
  tasks:

## Get current version
    - name: Get hostname
      cisco.ios.ios_hostname:
        state: gathered
      register: device_hostname

    - name: Check Code Version
      cisco.ios.ios_facts:
        gather_subset: min
      register: version

## Check hardware model
    - block:
      - name: Check switch model
        debug:
          msg: "Switch model: {{ version.ansible_facts.ansible_net_model }} -- Wrong switch model, skipping"
      - meta: end_host
      when: switch_model not in ansible_net_model

## Print current version
    - name: Print Hostname and Version
      debug:
        msg: "{{ device_hostname.gathered.hostname }} - {{ version.ansible_facts.ansible_net_version }}"

## Write successful upgrade to file 
    - block:
      - name: Image is Upgraded
        debug:
          msg: "Host: {{ device_hostname.gathered.hostname }} ---------  SUCCESS: Code Upgraded  --------- - Version: {{ version.ansible_facts.ansible_net_version }}"
      - lineinfile: 
          path: "/home/HT_Ansible_Demo/successful_upgrade.txt"
          regexp: "\\s{{ device_hostname.gathered.hostname }}$"
          line: "Successful Upgrade - Host: {{ device_hostname.gathered.hostname }} - Version: {{ ansible_net_version }}"
        delegate_to: localhost
      when: ansible_net_version == upgrade_ios_version

## Write unsuccessful upgrade to file
    - block:
      - name: Image is NOT Upgraded
        debug:
          msg: "Host: {{ device_hostname.gathered.hostname }} !!!!!!!!!!!  WARNING: Code is NOT Upgraded  !!!!!!!!!!! - Version: {{ version.ansible_facts.ansible_net_version }}"
      - lineinfile: 
          path: "/home/HT_Ansible_Demo/failed_upgrade.txt"
          regexp: "\\s{{ device_hostname.gathered.hostname }}$"
          line: "Failed Upgrade - Host: {{ device_hostname.gathered.hostname }} - Version: {{ ansible_net_version }}"
        delegate_to: localhost
      when: ansible_net_version != upgrade_ios_version


...
