---
# Ansible Playbook to backup config and write file to a folder

- name: Begin Config Backup
  hosts: office
  connection: local
  gather_facts: false
  strategy: free
  ignore_unreachable: true
  vars_files:
    - vault.yml
  vars:
    ansible_network_cli_ssh_type: libssh
    cli:
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:

    - name: Get hostname
      cisco.ios.ios_hostname:
        state: gathered
      register: device_hostname

    - name: Print hostname
      debug:
        msg: "{{ device_hostname.gathered.hostname }}"

# Show run, write to file, save file to folder
    - name: Backup Config 
      cisco.ios.ios_config:
        save_when: always
        backup: true
        backup_options:
          filename: "{{ device_hostname.gathered.hostname }}-backup.txt"
          dir_path: "/home/HT_Ansible_Demo/Config_Backups/"

    - name: Back up status
      debug: msg="Backup complete"

...
     